// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
}
export {}
