// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Button: typeof import('./src/components/antd/button/button.vue')['default']
    Header: typeof import('./src/components/desigin/header.vue')['default']
    TabPane: typeof import('./src/components/tabs/tab-pane.vue')['default']
    Tabs: typeof import('./src/components/tabs/tabs.vue')['default']
  }
}

export { }
