// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/button/button.vue')['default']
    CenterComponent: typeof import('./src/components/desigin/editor/component/center-component.vue')['default']
    Collapse: typeof import('./src/components/common/collapse/collapse.vue')['default']
    ComponentMenu: typeof import('./src/components/desigin/editor/component/leftComponent/component-menu.vue')['default']
    Echarts: typeof import('./src/components/common/echarts/echarts.vue')['default']
    Editor: typeof import('./src/components/desigin/editor/index.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/desigin/header.vue')['default']
    HeaderSetting: typeof import('./src/components/desigin/editor/component/rightComponent/component/headerSetting.vue')['default']
    InputNumber: typeof import('./src/components/common/inputNumber/inputNumber.vue')['default']
    Layer: typeof import('./src/components/desigin/editor/component/leftComponent/layer.vue')['default']
    LeftComponent: typeof import('./src/components/desigin/editor/component/left-component.vue')['default']
    Nav: typeof import('./src/components/desigin/editor/component/leftComponent/nav.vue')['default']
    RightComponent: typeof import('./src/components/desigin/editor/component/rightComponent.vue')['default']
    Select: typeof import('./src/components/common/select/select.vue')['default']
    SettingTreeRender: typeof import('./src/components/setting-tree-render/setting-tree-render.vue')['default']
    StyleSetting: typeof import('./src/components/desigin/editor/component/rightComponent/styleSetting.vue')['default']
    TabPane: typeof import('./src/components/tabs/tab-pane.vue')['default']
    Tabs: typeof import('./src/components/tabs/tabs.vue')['default']
    Tree: typeof import('./src/components/common/tree/tree.vue')['default']
    Upload: typeof import('./src/components/common/upload/upload.vue')['default']
  }
}

export { }
